# Generated by Django 5.1.6 on 2025-02-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darkweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
