# Generated by Django 5.1.6 on 2025-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkweb', '0002_rename_blog_id_comments_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(upload_to='images', verbose_name='foto : '),
        ),
    ]
